// Mock data para o sistema de ranking de doadores
import type { DonorRanking, CategoryRanking } from "./types/donor-ranking"
import { AVAILABLE_BADGES, calculateImpactScore } from "./types/donor-ranking"

export const mockDonorRankings: DonorRanking[] = [
  {
    id: "donor-1",
    name: "Maria Silva",
    avatar: "/professional-woman-avatar.png",
    isAnonymous: false,
    totalDonated: 125000,
    donationsCount: 87,
    projectsSupported: 23,
    impactScore: calculateImpactScore(125000, 87, 18),
    categoryDonations: [
      { category: "Alimentação", totalDonated: 45000, donationsCount: 32, rank: 1 },
      { category: "Educação", totalDonated: 35000, donationsCount: 25, rank: 2 },
      { category: "Saúde", totalDonated: 25000, donationsCount: 15, rank: 3 },
      { category: "Assistência Social", totalDonated: 20000, donationsCount: 15, rank: 5 },
    ],
    badges: [
      AVAILABLE_BADGES[0], // first-donation
      AVAILABLE_BADGES[1], // supporter-10
      AVAILABLE_BADGES[2], // supporter-50
      AVAILABLE_BADGES[3], // diversified
      AVAILABLE_BADGES[6], // streak-12
      AVAILABLE_BADGES[8], // donor-10k
      AVAILABLE_BADGES[9], // donor-100k
    ],
    memberSince: new Date("2023-06-15"),
    currentStreak: 18,
    longestStreak: 18,
  },
  {
    id: "donor-2",
    name: "João Empresas S.A.",
    avatar: "/corporate-building-logo.jpg",
    isAnonymous: false,
    totalDonated: 89000,
    donationsCount: 45,
    projectsSupported: 18,
    impactScore: calculateImpactScore(89000, 45, 12),
    categoryDonations: [
      { category: "Educação", totalDonated: 50000, donationsCount: 20, rank: 1 },
      { category: "Esporte", totalDonated: 25000, donationsCount: 15, rank: 1 },
      { category: "Cultura", totalDonated: 14000, donationsCount: 10, rank: 2 },
    ],
    badges: [AVAILABLE_BADGES[0], AVAILABLE_BADGES[1], AVAILABLE_BADGES[6], AVAILABLE_BADGES[8]],
    memberSince: new Date("2024-01-10"),
    currentStreak: 12,
    longestStreak: 12,
  },
  {
    id: "donor-3",
    name: "Anônimo",
    isAnonymous: true,
    totalDonated: 75000,
    donationsCount: 120,
    projectsSupported: 45,
    impactScore: calculateImpactScore(75000, 120, 24),
    categoryDonations: [
      { category: "Proteção Animal", totalDonated: 40000, donationsCount: 60, rank: 1 },
      { category: "Saúde", totalDonated: 20000, donationsCount: 35, rank: 1 },
      { category: "Alimentação", totalDonated: 15000, donationsCount: 25, rank: 4 },
    ],
    badges: [
      AVAILABLE_BADGES[0],
      AVAILABLE_BADGES[1],
      AVAILABLE_BADGES[2],
      AVAILABLE_BADGES[3],
      AVAILABLE_BADGES[5],
      AVAILABLE_BADGES[6],
      AVAILABLE_BADGES[8],
    ],
    memberSince: new Date("2022-03-20"),
    currentStreak: 24,
    longestStreak: 24,
  },
  {
    id: "donor-4",
    name: "Carlos Mendes",
    avatar: "/man-casual-avatar-smiling.jpg",
    isAnonymous: false,
    totalDonated: 52000,
    donationsCount: 38,
    projectsSupported: 12,
    impactScore: calculateImpactScore(52000, 38, 8),
    categoryDonations: [
      { category: "Moradia", totalDonated: 30000, donationsCount: 18, rank: 1 },
      { category: "Assistência Social", totalDonated: 22000, donationsCount: 20, rank: 2 },
    ],
    badges: [AVAILABLE_BADGES[0], AVAILABLE_BADGES[1], AVAILABLE_BADGES[5], AVAILABLE_BADGES[7], AVAILABLE_BADGES[8]],
    memberSince: new Date("2024-04-05"),
    currentStreak: 8,
    longestStreak: 8,
  },
  {
    id: "donor-5",
    name: "Ana Paula Costa",
    avatar: "/woman-young-professional-avatar.jpg",
    isAnonymous: false,
    totalDonated: 38500,
    donationsCount: 65,
    projectsSupported: 28,
    impactScore: calculateImpactScore(38500, 65, 15),
    categoryDonations: [
      { category: "Alimentação", totalDonated: 12000, donationsCount: 20, rank: 3 },
      { category: "Educação", totalDonated: 10000, donationsCount: 15, rank: 5 },
      { category: "Saúde", totalDonated: 8000, donationsCount: 15, rank: 4 },
      { category: "Proteção Animal", totalDonated: 5000, donationsCount: 10, rank: 3 },
      { category: "Cultura", totalDonated: 3500, donationsCount: 5, rank: 5 },
    ],
    badges: [
      AVAILABLE_BADGES[0],
      AVAILABLE_BADGES[1],
      AVAILABLE_BADGES[2],
      AVAILABLE_BADGES[3],
      AVAILABLE_BADGES[5],
      AVAILABLE_BADGES[6],
      AVAILABLE_BADGES[7],
      AVAILABLE_BADGES[8],
    ],
    memberSince: new Date("2023-09-12"),
    currentStreak: 15,
    longestStreak: 15,
  },
  {
    id: "donor-6",
    name: "Fundação Esperança",
    avatar: "/foundation-charity-logo-heart.jpg",
    isAnonymous: false,
    totalDonated: 320000,
    donationsCount: 150,
    projectsSupported: 55,
    impactScore: calculateImpactScore(320000, 150, 36),
    categoryDonations: [
      { category: "Educação", totalDonated: 120000, donationsCount: 50, rank: 1 },
      { category: "Saúde", totalDonated: 80000, donationsCount: 40, rank: 1 },
      { category: "Alimentação", totalDonated: 60000, donationsCount: 30, rank: 2 },
      { category: "Assistência Social", totalDonated: 40000, donationsCount: 20, rank: 1 },
      { category: "Moradia", totalDonated: 20000, donationsCount: 10, rank: 2 },
    ],
    badges: AVAILABLE_BADGES, // Todos os badges
    memberSince: new Date("2022-01-01"),
    currentStreak: 36,
    longestStreak: 36,
  },
  {
    id: "donor-7",
    name: "Roberto Almeida",
    avatar: "/man-elderly-avatar-kind.jpg",
    isAnonymous: false,
    totalDonated: 28000,
    donationsCount: 22,
    projectsSupported: 8,
    impactScore: calculateImpactScore(28000, 22, 6),
    categoryDonations: [
      { category: "Saúde", totalDonated: 18000, donationsCount: 12, rank: 2 },
      { category: "Assistência Social", totalDonated: 10000, donationsCount: 10, rank: 4 },
    ],
    badges: [AVAILABLE_BADGES[0], AVAILABLE_BADGES[1], AVAILABLE_BADGES[5], AVAILABLE_BADGES[7], AVAILABLE_BADGES[8]],
    memberSince: new Date("2024-06-20"),
    currentStreak: 6,
    longestStreak: 6,
  },
  {
    id: "donor-8",
    name: "Tech4Good Ltda",
    avatar: "/modern-tech-logo.png",
    isAnonymous: false,
    totalDonated: 95000,
    donationsCount: 35,
    projectsSupported: 15,
    impactScore: calculateImpactScore(95000, 35, 10),
    categoryDonations: [
      { category: "Educação", totalDonated: 70000, donationsCount: 25, rank: 3 },
      { category: "Cultura", totalDonated: 25000, donationsCount: 10, rank: 1 },
    ],
    badges: [AVAILABLE_BADGES[0], AVAILABLE_BADGES[1], AVAILABLE_BADGES[5], AVAILABLE_BADGES[6], AVAILABLE_BADGES[8]],
    memberSince: new Date("2024-02-15"),
    currentStreak: 10,
    longestStreak: 10,
  },
  {
    id: "donor-9",
    name: "Anônimo",
    isAnonymous: true,
    totalDonated: 15000,
    donationsCount: 30,
    projectsSupported: 15,
    impactScore: calculateImpactScore(15000, 30, 5),
    categoryDonations: [
      { category: "Proteção Animal", totalDonated: 10000, donationsCount: 20, rank: 2 },
      { category: "Alimentação", totalDonated: 5000, donationsCount: 10, rank: 8 },
    ],
    badges: [AVAILABLE_BADGES[0], AVAILABLE_BADGES[1], AVAILABLE_BADGES[5], AVAILABLE_BADGES[7], AVAILABLE_BADGES[8]],
    memberSince: new Date("2024-07-01"),
    currentStreak: 5,
    longestStreak: 5,
  },
  {
    id: "donor-10",
    name: "Patricia Fernandes",
    avatar: "/placeholder-enryt.png",
    isAnonymous: false,
    totalDonated: 42000,
    donationsCount: 55,
    projectsSupported: 20,
    impactScore: calculateImpactScore(42000, 55, 11),
    categoryDonations: [
      { category: "Alimentação", totalDonated: 18000, donationsCount: 25, rank: 2 },
      { category: "Proteção Animal", totalDonated: 12000, donationsCount: 15, rank: 4 },
      { category: "Saúde", totalDonated: 8000, donationsCount: 10, rank: 5 },
      { category: "Esporte", totalDonated: 4000, donationsCount: 5, rank: 3 },
    ],
    badges: [
      AVAILABLE_BADGES[0],
      AVAILABLE_BADGES[1],
      AVAILABLE_BADGES[2],
      AVAILABLE_BADGES[3],
      AVAILABLE_BADGES[5],
      AVAILABLE_BADGES[6],
      AVAILABLE_BADGES[7],
      AVAILABLE_BADGES[8],
    ],
    memberSince: new Date("2023-12-01"),
    currentStreak: 11,
    longestStreak: 11,
  },
]

// Ranking por categoria
export const mockCategoryRankings: CategoryRanking[] = [
  {
    category: "Alimentação",
    icon: "Utensils",
    color: "bg-orange-500",
    totalDonated: 155000,
    donorsCount: 245,
    topDonors: [
      { id: "donor-1", name: "Maria Silva", totalDonated: 45000, impactScore: 13795, rank: 1, isAnonymous: false },
      {
        id: "donor-6",
        name: "Fundação Esperança",
        totalDonated: 60000,
        impactScore: 33470,
        rank: 2,
        isAnonymous: false,
      },
      {
        id: "donor-10",
        name: "Patricia Fernandes",
        totalDonated: 18000,
        impactScore: 4695,
        rank: 3,
        isAnonymous: false,
      },
      { id: "donor-3", name: "Anônimo", totalDonated: 15000, impactScore: 8580, rank: 4, isAnonymous: true },
      { id: "donor-5", name: "Ana Paula Costa", totalDonated: 12000, impactScore: 4475, rank: 5, isAnonymous: false },
    ],
  },
  {
    category: "Educação",
    icon: "GraduationCap",
    color: "bg-blue-500",
    totalDonated: 285000,
    donorsCount: 312,
    topDonors: [
      {
        id: "donor-6",
        name: "Fundação Esperança",
        totalDonated: 120000,
        impactScore: 33470,
        rank: 1,
        isAnonymous: false,
      },
      { id: "donor-8", name: "Tech4Good Ltda", totalDonated: 70000, impactScore: 9875, rank: 2, isAnonymous: false },
      {
        id: "donor-2",
        name: "João Empresas S.A.",
        totalDonated: 50000,
        impactScore: 9365,
        rank: 3,
        isAnonymous: false,
      },
      { id: "donor-1", name: "Maria Silva", totalDonated: 35000, impactScore: 13795, rank: 4, isAnonymous: false },
      { id: "donor-5", name: "Ana Paula Costa", totalDonated: 10000, impactScore: 4475, rank: 5, isAnonymous: false },
    ],
  },
  {
    category: "Saúde",
    icon: "Heart",
    color: "bg-red-500",
    totalDonated: 159000,
    donorsCount: 198,
    topDonors: [
      {
        id: "donor-6",
        name: "Fundação Esperança",
        totalDonated: 80000,
        impactScore: 33470,
        rank: 1,
        isAnonymous: false,
      },
      { id: "donor-3", name: "Anônimo", totalDonated: 20000, impactScore: 8580, rank: 2, isAnonymous: true },
      { id: "donor-7", name: "Roberto Almeida", totalDonated: 18000, impactScore: 3030, rank: 3, isAnonymous: false },
      { id: "donor-1", name: "Maria Silva", totalDonated: 25000, impactScore: 13795, rank: 4, isAnonymous: false },
      { id: "donor-5", name: "Ana Paula Costa", totalDonated: 8000, impactScore: 4475, rank: 5, isAnonymous: false },
    ],
  },
  {
    category: "Proteção Animal",
    icon: "PawPrint",
    color: "bg-green-500",
    totalDonated: 67000,
    donorsCount: 156,
    topDonors: [
      { id: "donor-3", name: "Anônimo", totalDonated: 40000, impactScore: 8580, rank: 1, isAnonymous: true },
      { id: "donor-9", name: "Anônimo", totalDonated: 10000, impactScore: 1750, rank: 2, isAnonymous: true },
      {
        id: "donor-10",
        name: "Patricia Fernandes",
        totalDonated: 12000,
        impactScore: 4695,
        rank: 3,
        isAnonymous: false,
      },
      { id: "donor-5", name: "Ana Paula Costa", totalDonated: 5000, impactScore: 4475, rank: 4, isAnonymous: false },
    ],
  },
  {
    category: "Assistência Social",
    icon: "HandHeart",
    color: "bg-purple-500",
    totalDonated: 92000,
    donorsCount: 178,
    topDonors: [
      {
        id: "donor-6",
        name: "Fundação Esperança",
        totalDonated: 40000,
        impactScore: 33470,
        rank: 1,
        isAnonymous: false,
      },
      { id: "donor-4", name: "Carlos Mendes", totalDonated: 22000, impactScore: 5550, rank: 2, isAnonymous: false },
      { id: "donor-1", name: "Maria Silva", totalDonated: 20000, impactScore: 13795, rank: 3, isAnonymous: false },
      { id: "donor-7", name: "Roberto Almeida", totalDonated: 10000, impactScore: 3030, rank: 4, isAnonymous: false },
    ],
  },
  {
    category: "Moradia",
    icon: "Home",
    color: "bg-amber-500",
    totalDonated: 50000,
    donorsCount: 89,
    topDonors: [
      { id: "donor-4", name: "Carlos Mendes", totalDonated: 30000, impactScore: 5550, rank: 1, isAnonymous: false },
      {
        id: "donor-6",
        name: "Fundação Esperança",
        totalDonated: 20000,
        impactScore: 33470,
        rank: 2,
        isAnonymous: false,
      },
    ],
  },
  {
    category: "Cultura",
    icon: "Palette",
    color: "bg-pink-500",
    totalDonated: 42500,
    donorsCount: 67,
    topDonors: [
      { id: "donor-8", name: "Tech4Good Ltda", totalDonated: 25000, impactScore: 9875, rank: 1, isAnonymous: false },
      {
        id: "donor-2",
        name: "João Empresas S.A.",
        totalDonated: 14000,
        impactScore: 9365,
        rank: 2,
        isAnonymous: false,
      },
      { id: "donor-5", name: "Ana Paula Costa", totalDonated: 3500, impactScore: 4475, rank: 3, isAnonymous: false },
    ],
  },
  {
    category: "Esporte",
    icon: "Trophy",
    color: "bg-cyan-500",
    totalDonated: 29000,
    donorsCount: 45,
    topDonors: [
      {
        id: "donor-2",
        name: "João Empresas S.A.",
        totalDonated: 25000,
        impactScore: 9365,
        rank: 1,
        isAnonymous: false,
      },
      {
        id: "donor-10",
        name: "Patricia Fernandes",
        totalDonated: 4000,
        impactScore: 4695,
        rank: 2,
        isAnonymous: false,
      },
    ],
  },
]

// Estatísticas gerais
export const donorStats = {
  totalDonated: 880500,
  totalDonors: 1245,
  totalDonations: 4523,
  totalProjectsSupported: 156,
  averageDonation: 195,
}
