// Mock data alinhado com o Blueprint IAC
import { type ImpactActionCard, IacStatus, type Evidence } from "./types/iac"
import { type FundingProject, FundingStatus } from "./types/funding"
import type { ImpactRecord } from "./types/impact-registry"

export const mockEvidences: Evidence[] = [
  {
    id: "ev-1",
    url: "/community-kitchen-serving-meals.jpg",
    type: "PHOTO",
    timestamp: new Date("2025-12-08T10:30:00"),
    gpsCoordinates: { lat: -23.5505, lng: -46.634 },
    deviceSignature: "STHATION-APP-v1.0-DEVICE-abc123",
    contentHash: "sha256:a1b2c3d4e5f6...",
    description: "Distribuicao de refeicoes - Turno da manha",
  },
  {
    id: "ev-2",
    url: "/foundation-charity-logo-heart.jpg",
    type: "PHOTO",
    timestamp: new Date("2025-12-09T14:15:00"),
    gpsCoordinates: { lat: -23.5510, lng: -46.6345 },
    deviceSignature: "STHATION-APP-v1.0-DEVICE-abc123",
    contentHash: "sha256:f6e5d4c3b2a1...",
    description: "Registro de beneficiarios atendidos no dia",
  },
  {
    id: "ev-3",
    url: "/report-document.jpg",
    type: "DOCUMENT",
    timestamp: new Date("2025-12-07T09:00:00"),
    gpsCoordinates: { lat: -23.5505, lng: -46.634 },
    deviceSignature: "STHATION-APP-v1.0-DEVICE-abc123",
    contentHash: "sha256:123456789abc...",
    description: "Relatorio mensal de atendimentos com lista de beneficiarios",
  },
  {
    id: "ev-4",
    url: "/notas-fiscais.jpg",
    type: "DOCUMENT",
    timestamp: new Date("2025-12-10T08:00:00"),
    gpsCoordinates: { lat: -23.5505, lng: -46.634 },
    deviceSignature: "STHATION-APP-v1.0-DEVICE-def456",
    contentHash: "sha256:doc987654321...",
    description: "Notas fiscais de compra de alimentos e insumos",
  },
]

// IACs sao projetos SOCIAIS - passam pelo VCA de Checkers
// Projetos AMBIENTAIS NAO usam IAC/VCA, sao validados por Analistas Certificadores
export const mockIACs: ImpactActionCard[] = [
  {
    id: "iac-1",
    institutionId: "inst-1",
    projectId: "proj-1",
    title: "Cozinha Comunitaria Esperanca",
    description:
      "Distribuicao de 3.000 refeicoes/mes para familias em situacao de vulnerabilidade alimentar na zona leste de SP.",
    tsbCategory: "TSB-01",
    location: {
      name: "Sao Paulo, SP",
      coordinates: { lat: -23.5505, lng: -46.634 },
    },
    targetImpact: "Alimentar 1.500 pessoas/mes, reduzir inseguranca alimentar em 40%",
    startDate: new Date("2025-01-15"),
    endDate: new Date("2025-12-31"),
    budget: 250000,
    status: IacStatus.VALIDATED,
    evidences: mockEvidences,
    auditLog: [
      { timestamp: new Date("2025-01-15T10:00:00"), action: "IAC criado", userId: "user-1" },
      { timestamp: new Date("2025-01-16T09:30:00"), action: "Primeira evidencia adicionada", userId: "user-1" },
      { timestamp: new Date("2025-06-20T14:00:00"), action: "IAC submetido para VCA", userId: "user-1" },
      { timestamp: new Date("2025-07-05T16:45:00"), action: "VCA aprovado (87% consenso)", userId: "system" },
    ],
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-07-05"),
    submittedAt: new Date("2025-06-20"),
    validatedAt: new Date("2025-07-05"),
    institution: {
      id: "inst-1",
      name: "Associacao Vida Nova",
      logo: "/foundation-charity-logo-heart.jpg",
    },
  },
  {
    id: "iac-2",
    institutionId: "inst-2",
    projectId: "proj-2",
    title: "Escola de Informatica Rocinha",
    description: "Curso de programacao e alfabetizacao digital para 200 jovens da comunidade da Rocinha.",
    tsbCategory: "TSB-02",
    location: {
      name: "Rio de Janeiro, RJ",
      coordinates: { lat: -22.9879, lng: -43.2474 },
    },
    targetImpact: "Capacitar 200 jovens em programacao, inserir 60% no mercado de trabalho",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-11-30"),
    budget: 480000,
    status: IacStatus.SUBMITTED,
    evidences: mockEvidences.slice(0, 3),
    auditLog: [
      { timestamp: new Date("2025-02-01T08:00:00"), action: "IAC criado", userId: "user-2" },
      { timestamp: new Date("2025-08-15T11:00:00"), action: "Evidencias completas (8)", userId: "user-2" },
      { timestamp: new Date("2025-12-09T10:00:00"), action: "IAC submetido para VCA", userId: "user-2" },
    ],
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-12-09"),
    submittedAt: new Date("2025-12-09"),
    institution: {
      id: "inst-2",
      name: "ONG Futuro Tech",
      logo: "/education-classroom.jpg",
    },
  },
  {
    id: "iac-3",
    institutionId: "inst-3",
    projectId: "proj-3",
    title: "Abrigo Temporario Porto Alegre",
    description:
      "Apoio emergencial para 100 familias desabrigadas pelas enchentes no RS com moradia, alimentacao e suporte psicologico.",
    tsbCategory: "TSB-03",
    location: {
      name: "Porto Alegre, RS",
      coordinates: { lat: -30.0346, lng: -51.2177 },
    },
    targetImpact: "Abrigar 100 familias por 3 meses, reinsercao social de 70%",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-12-15"),
    budget: 180000,
    status: IacStatus.EXECUTING,
    evidences: mockEvidences.slice(0, 2),
    auditLog: [
      { timestamp: new Date("2025-03-01T09:00:00"), action: "IAC criado", userId: "user-3" },
      { timestamp: new Date("2025-03-02T10:30:00"), action: "Status alterado para EXECUTING", userId: "system" },
    ],
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2025-12-08"),
    institution: {
      id: "inst-3",
      name: "Casa de Acolhimento Lar Feliz",
      logo: "/foundation-charity-logo-heart.jpg",
    },
  },
  {
    id: "iac-4",
    institutionId: "inst-4",
    projectId: "proj-4",
    title: "Capacitacao Profissional Jovem Cidadao",
    description: "Cursos de eletrica, mecanica e costura para 300 jovens de comunidades carentes em Curitiba.",
    tsbCategory: "TSB-02",
    location: {
      name: "Curitiba, PR",
      coordinates: { lat: -25.4284, lng: -49.2733 },
    },
    targetImpact: "Capacitar 300 jovens, gerar renda para 200 familias",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2026-03-31"),
    budget: 320000,
    status: IacStatus.DRAFT,
    evidences: [],
    auditLog: [{ timestamp: new Date("2025-12-07T14:00:00"), action: "IAC criado", userId: "user-4" }],
    createdAt: new Date("2025-12-07"),
    updatedAt: new Date("2025-12-07"),
    institution: {
      id: "inst-4",
      name: "Instituto Cidadao do Futuro",
      logo: "/education-classroom.jpg",
    },
  },
  {
    id: "iac-5",
    institutionId: "inst-1",
    projectId: "proj-5",
    title: "Programa Saude na Comunidade",
    description: "Atendimento medico e odontologico gratuito para 2.000 pessoas em comunidades sem acesso a saude basica.",
    tsbCategory: "TSB-04",
    location: {
      name: "Recife, PE",
      coordinates: { lat: -8.0476, lng: -34.877 },
    },
    targetImpact: "Atender 2.000 pessoas, realizar 500 consultas/mes",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2025-05-31"),
    budget: 420000,
    status: IacStatus.MINTED,
    evidences: mockEvidences,
    auditLog: [
      { timestamp: new Date("2024-06-01T10:00:00"), action: "IAC criado", userId: "user-1" },
      { timestamp: new Date("2024-12-15T09:00:00"), action: "IAC submetido para VCA", userId: "user-1" },
      { timestamp: new Date("2025-01-10T14:30:00"), action: "VCA aprovado (92% consenso)", userId: "system" },
      {
        timestamp: new Date("2025-02-01T10:00:00"),
        action: "NOBIS mintado - Inscrito no Bitcoin",
        userId: "system",
        details: "Ordinal ID: abc123...",
      },
    ],
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2025-02-01"),
    submittedAt: new Date("2024-12-15"),
    validatedAt: new Date("2025-01-10"),
    mintedAt: new Date("2025-02-01"),
    institution: {
      id: "inst-1",
      name: "Associacao Vida Nova",
      logo: "/foundation-charity-logo-heart.jpg",
    },
  },
]

// Estes são os projetos que aparecem na página inicial para doadores
export const mockFundingProjects: FundingProject[] = [
  {
    id: "fund-1",
    iacId: "",
    institutionId: "inst-5",
    title: "Cozinha Solidária - Heliópolis",
    description:
      "Fornecimento de 500 refeições diárias para famílias em vulnerabilidade alimentar na comunidade de Heliópolis. Inclui café da manhã e almoço nutritivo preparado por cozinheiros da própria comunidade.",
    category: "Alimentação e Segurança Alimentar",
    tsbCategory: "TSB-01",
    location: {
      name: "Heliópolis",
      state: "SP",
      coordinates: { lat: -23.5974, lng: -46.5844 },
    },
    costModel: {
      com: 15000,
      fri: 0.2,
      pco: 3000,
      cdp: 45000,
      metaTotal: 48000,
    },
    currentAmount: 32500,
    donorsCount: 127,
    proxyCategory: "Alimentação",
    proxyValuePerUnit: 1.07,
    proxyUnit: "refeição/dia",
    estimatedBeneficiaries: 500,
    status: FundingStatus.FUNDING,
    publishedAt: new Date("2025-11-01"),
    deadline: new Date("2025-12-31"),
    coverImage: "/community-kitchen-serving-meals.jpg",
    images: [],
  },
  {
    id: "fund-2",
    iacId: "",
    institutionId: "inst-6",
    title: "Escola de Informática - Rocinha",
    description:
      "Curso de programação e alfabetização digital para 200 jovens da comunidade da Rocinha. Formação de 6 meses com certificação reconhecida pelo mercado e mentoria para inserção profissional.",
    category: "Educação e Qualificação Profissional",
    tsbCategory: "TSB-02",
    location: {
      name: "Rocinha",
      state: "RJ",
      coordinates: { lat: -22.9879, lng: -43.2474 },
    },
    costModel: {
      com: 25000,
      fri: 0.15,
      pco: 3750,
      cdp: 80000,
      metaTotal: 83750,
    },
    currentAmount: 83750,
    donorsCount: 312,
    proxyCategory: "Educação",
    proxyValuePerUnit: 500,
    proxyUnit: "aluno/mês",
    estimatedBeneficiaries: 200,
    status: FundingStatus.FUNDED,
    publishedAt: new Date("2025-09-15"),
    fundedAt: new Date("2025-11-20"),
    deadline: new Date("2025-12-15"),
    coverImage: "/young-people-learning-computers-classroom.jpg",
    images: [],
  },
  {
    id: "fund-3",
    iacId: "",
    institutionId: "inst-7",
    title: "Abrigo Temporário - Porto Alegre",
    description:
      "Apoio emergencial para 100 famílias desabrigadas pelas enchentes no RS. Inclui moradia temporária, alimentação, kit higiene e suporte psicológico por 3 meses.",
    category: "Assistência Social",
    tsbCategory: "TSB-03",
    location: {
      name: "Porto Alegre",
      state: "RS",
      coordinates: { lat: -30.0346, lng: -51.2177 },
    },
    costModel: {
      com: 20000,
      fri: 0.25,
      pco: 5000,
      cdp: 120000,
      metaTotal: 125000,
    },
    currentAmount: 67800,
    donorsCount: 445,
    proxyCategory: "Assistência Social",
    proxyValuePerUnit: 375,
    proxyUnit: "família/mês",
    estimatedBeneficiaries: 100,
    status: FundingStatus.FUNDING,
    publishedAt: new Date("2025-10-20"),
    deadline: new Date("2026-01-20"),
    coverImage: "/flood-relief-shelter-families.jpg",
    images: [],
  },
  {
    id: "fund-4",
    iacId: "",
    institutionId: "inst-8",
    title: "Castração Solidária - Fortaleza",
    description:
      "Campanha de castração gratuita para 1.000 animais de rua em Fortaleza. Inclui cirurgia, vacinas, vermifugação e microchipagem para controle populacional humanitário.",
    category: "Proteção Animal",
    tsbCategory: "TSB-04",
    location: {
      name: "Fortaleza",
      state: "CE",
      coordinates: { lat: -3.7172, lng: -38.5433 },
    },
    costModel: {
      com: 8000,
      fri: 0.1,
      pco: 800,
      cdp: 35000,
      metaTotal: 35800,
    },
    currentAmount: 12400,
    donorsCount: 89,
    proxyCategory: "Proteção Animal",
    proxyValuePerUnit: 90,
    proxyUnit: "animal",
    estimatedBeneficiaries: 1000,
    status: FundingStatus.FUNDING,
    publishedAt: new Date("2025-12-01"),
    deadline: new Date("2026-02-28"),
    coverImage: "/veterinarian-helping-stray-dogs-cats.jpg",
    images: [],
  },
  {
    id: "fund-5",
    iacId: "iac-3",
    institutionId: "inst-3",
    title: "Abrigo Temporario Porto Alegre",
    description:
      "Apoio emergencial para 100 familias desabrigadas pelas enchentes no RS. Moradia temporaria, alimentacao, kit higiene e suporte psicologico. Projeto ja em execucao com evidencias registradas.",
    category: "Assistencia Social",
    tsbCategory: "TSB-03",
    location: {
      name: "Porto Alegre",
      state: "RS",
      coordinates: { lat: -30.0346, lng: -51.2177 },
    },
    costModel: {
      com: 18000,
      fri: 0.15,
      pco: 2700,
      cdp: 177300,
      metaTotal: 180000,
    },
    currentAmount: 180000,
    donorsCount: 523,
    proxyCategory: "Assistencia Social",
    proxyValuePerUnit: 375,
    proxyUnit: "familia/mes",
    estimatedBeneficiaries: 100,
    status: FundingStatus.EXECUTING,
    publishedAt: new Date("2025-01-15"),
    fundedAt: new Date("2025-02-28"),
    coverImage: "/foundation-charity-logo-heart.jpg",
    images: [],
  },
]

// Estes são os ativos que já passaram por todo o fluxo: Captação → Execução → VCA → Mint
export interface MintedNobis {
  id: string
  iacId: string
  title: string
  description: string
  category: string
  tsbCategory: string
  location: string
  institution: {
    id: string
    name: string
    logo: string
  }
  generationCost: number // Custo total para gerar este impacto
  carbonCredits: number
  impactUnits: number
  impactUnit: string
  impactScore: number // Pontuação de impacto gerada
  // Bitcoin inscription
  inscriptionId: string | null
  inscribedAt: Date | null
  // Status
  status: "VALIDATED" | "INSCRIBED"
  // Validação
  vcaScore: number
  checkersCount: number
  validatedAt: Date
  mintedAt: Date
  // Imagem
  coverImage: string
}

// NOBIS sao tokens gerados de projetos SOCIAIS que passaram pelo fluxo completo
export const mockMintedNobis: MintedNobis[] = [
  {
    id: "nobis-1",
    iacId: "iac-5",
    title: "Programa Saude na Comunidade",
    description:
      "Atendimento medico e odontologico gratuito para 2.000 pessoas em comunidades sem acesso a saude basica em Recife.",
    category: "Saude",
    tsbCategory: "TSB-04",
    location: "Recife, PE",
    institution: {
      id: "inst-1",
      name: "Associacao Vida Nova",
      logo: "/foundation-charity-logo-heart.jpg",
    },
    generationCost: 420000,
    carbonCredits: 0,
    impactUnits: 2000,
    impactUnit: "pessoas atendidas",
    impactScore: 9200,
    inscriptionId: "ord:abc123def456ghi789",
    inscribedAt: new Date("2025-02-15"),
    status: "INSCRIBED",
    vcaScore: 92,
    checkersCount: 10,
    validatedAt: new Date("2025-01-10"),
    mintedAt: new Date("2025-02-01"),
    coverImage: "/foundation-charity-logo-heart.jpg",
  },
  {
    id: "nobis-2",
    iacId: "iac-completed-1",
    title: "Cozinha Comunitaria Heliopolis",
    description:
      "15.000 refeicoes distribuidas para familias em vulnerabilidade alimentar. 500 familias beneficiadas durante 30 dias.",
    category: "Alimentacao",
    tsbCategory: "TSB-01",
    location: "Sao Paulo, SP",
    institution: {
      id: "inst-5",
      name: "Associacao Comunitaria Heliopolis",
      logo: "/community-kitchen-serving-meals.jpg",
    },
    generationCost: 48000,
    carbonCredits: 0,
    impactUnits: 15000,
    impactUnit: "refeicoes distribuidas",
    impactScore: 7500,
    inscriptionId: null,
    inscribedAt: null,
    status: "VALIDATED",
    vcaScore: 88,
    checkersCount: 10,
    validatedAt: new Date("2025-09-20"),
    mintedAt: new Date("2025-10-01"),
    coverImage: "/community-kitchen-serving-meals.jpg",
  },
  {
    id: "nobis-3",
    iacId: "iac-completed-2",
    title: "Escola de Informatica Rocinha",
    description:
      "200 jovens capacitados em programacao e alfabetizacao digital. 120 inseridos no mercado de trabalho apos formacao de 6 meses.",
    category: "Educacao",
    tsbCategory: "TSB-02",
    location: "Rio de Janeiro, RJ",
    institution: {
      id: "inst-2",
      name: "ONG Futuro Tech",
      logo: "/education-classroom.jpg",
    },
    generationCost: 83750,
    carbonCredits: 0,
    impactUnits: 200,
    impactUnit: "jovens capacitados",
    impactScore: 9500,
    inscriptionId: "ord:xyz789abc123def456",
    inscribedAt: new Date("2025-08-20"),
    status: "INSCRIBED",
    vcaScore: 95,
    checkersCount: 10,
    validatedAt: new Date("2025-07-15"),
    mintedAt: new Date("2025-08-01"),
    coverImage: "/education-classroom.jpg",
  },
  {
    id: "nobis-4",
    iacId: "iac-completed-3",
    title: "Abrigo Temporario Porto Alegre",
    description:
      "100 familias desabrigadas acolhidas por 3 meses com moradia, alimentacao e suporte psicologico. 70% reinseridas socialmente.",
    category: "Assistencia Social",
    tsbCategory: "TSB-03",
    location: "Porto Alegre, RS",
    institution: {
      id: "inst-3",
      name: "Casa de Acolhimento Lar Feliz",
      logo: "/foundation-charity-logo-heart.jpg",
    },
    generationCost: 125000,
    carbonCredits: 0,
    impactUnits: 100,
    impactUnit: "familias acolhidas",
    impactScore: 4000,
    inscriptionId: null,
    inscribedAt: null,
    status: "VALIDATED",
    vcaScore: 84,
    checkersCount: 10,
    validatedAt: new Date("2025-10-05"),
    mintedAt: new Date("2025-10-20"),
    coverImage: "/foundation-charity-logo-heart.jpg",
  },
  {
    id: "nobis-5",
    iacId: "iac-completed-4",
    title: "Capacitacao Profissional Jovem Cidadao",
    description:
      "300 jovens de comunidades carentes capacitados em eletrica, mecanica e costura. 200 familias com renda gerada.",
    category: "Capacitacao",
    tsbCategory: "TSB-02",
    location: "Curitiba, PR",
    institution: {
      id: "inst-4",
      name: "Instituto Cidadao do Futuro",
      logo: "/education-classroom.jpg",
    },
    generationCost: 35800,
    carbonCredits: 0,
    impactUnits: 300,
    impactUnit: "jovens capacitados",
    impactScore: 18000,
    inscriptionId: "ord:mno456pqr789stu012",
    inscribedAt: new Date("2025-06-10"),
    status: "INSCRIBED",
    vcaScore: 91,
    checkersCount: 10,
    validatedAt: new Date("2025-05-01"),
    mintedAt: new Date("2025-05-15"),
    coverImage: "/education-classroom.jpg",
  },
]

// Hall de Impacto - Registros de trilha completa
export const mockImpactRecords: ImpactRecord[] = [
  // FLUXO SOCIAL - Com doações, checkers, certificadores
  {
    id: "impact-social-1",
    type: "SOCIAL",
    title: "Cozinha Solidária - Heliópolis",
    description:
      "Fornecimento de 15.000 refeições para famílias em vulnerabilidade alimentar. Projeto executado com sucesso durante 30 dias, impactando diretamente 500 famílias da comunidade.",
    category: "Alimentação e Segurança Alimentar",
    organization: {
      id: "inst-5",
      name: "Associação Comunitária Heliópolis",
      logo: "/foundation-charity-logo-heart.jpg",
      type: "INSTITUICAO_SOCIAL",
    },
    location: {
      name: "Heliópolis",
      state: "SP",
      coordinates: { lat: -23.5974, lng: -46.5844 },
    },
    coverImage: "/community-kitchen-serving-meals.jpg",
    timeline: [
      {
        id: "tl-1",
        phase: "CAPTACAO",
        title: "Projeto publicado para captação",
        description: "Card de captação publicado na plataforma STHATION",
        timestamp: new Date("2025-08-01T10:00:00"),
        actor: { id: "inst-5", name: "Associação Comunitária Heliópolis", role: "Instituição" },
      },
      {
        id: "tl-2",
        phase: "DOACAO",
        title: "Meta de captação atingida",
        description: "R$ 48.000 arrecadados de 127 doadores",
        timestamp: new Date("2025-08-25T14:30:00"),
        data: { totalRaised: 48000, donorsCount: 127 },
      },
      {
        id: "tl-3",
        phase: "EXECUCAO",
        title: "Início da execução",
        description: "Cozinha montada e primeira semana de operação",
        timestamp: new Date("2025-09-01T08:00:00"),
        actor: { id: "inst-5", name: "Associação Comunitária Heliópolis", role: "Instituição" },
      },
      {
        id: "tl-4",
        phase: "EXECUCAO",
        title: "Registro de evidências",
        description: "12 evidências registradas: fotos, vídeos e relatórios",
        timestamp: new Date("2025-09-30T18:00:00"),
        hash: "sha256:abc123def456...",
      },
      {
        id: "tl-5",
        phase: "CHECAGEM",
        title: "Validação por Checkers",
        description: "10 checkers validaram o projeto com 94% de consenso",
        timestamp: new Date("2025-10-05T16:00:00"),
        data: { checkersCount: 10, consensusPercent: 94 },
      },
      {
        id: "tl-6",
        phase: "CERTIFICACAO",
        title: "Certificação técnica aprovada",
        description: "Analista certificador validou metodologia e impacto",
        timestamp: new Date("2025-10-10T11:00:00"),
        actor: { id: "cert-1", name: "Dr. Maria Santos", role: "Analista Certificador" },
      },
      {
        id: "tl-7",
        phase: "INSCRICAO",
        title: "Inscrito no Bitcoin",
        description: "Registro imutável criado na blockchain Bitcoin",
        timestamp: new Date("2025-10-12T09:00:00"),
        data: { inscriptionId: "ord:soc123abc456def789", blockHeight: 870123 },
      },
      {
        id: "tl-8",
        phase: "CONCLUIDO",
        title: "Impacto registrado no Hall",
        description: "Disponível no Hall de Impacto da STHATION",
        timestamp: new Date("2025-10-12T10:00:00"),
      },
    ],
    currentPhase: "CONCLUIDO",
    metrics: {
      totalInvested: 48000,
      beneficiaries: 500,
      impactUnits: 15000,
      impactUnit: "refeições servidas",
      impactScore: 8500,
    },
    validation: {
      checkersCount: 10,
      checkersApproval: 94,
      certifiersCount: 1,
      certifiersApproval: 100,
      validatedAt: new Date("2025-10-10T11:00:00"),
    },
    inscription: {
      txid: "abc123def456789xyz",
      inscriptionId: "ord:soc123abc456def789",
      inscribedAt: new Date("2025-10-12T09:00:00"),
      blockHeight: 870123,
    },
    status: "INSCRITO",
    createdAt: new Date("2025-08-01T10:00:00"),
    updatedAt: new Date("2025-10-12T10:00:00"),
    availableForTrading: true,
    tradingPlatformUrl: "https://trading.sthation.io/nobis/soc123",
  },
  // FLUXO AMBIENTAL - Registro manual pela empresa
  {
    id: "impact-ambiental-1",
    type: "AMBIENTAL",
    title: "Reflorestamento Cerrado - Goiás",
    description:
      "Plantio de 25.000 árvores nativas do bioma Cerrado em área degradada por pastagem. Sistema de monitoramento IoT para acompanhar crescimento e sobrevivência das mudas.",
    category: "Reflorestamento",
    organization: {
      id: "emp-1",
      name: "Coop. Terra Fértil",
      logo: "/solar-energy-logo.png",
      type: "EMPRESA_AMBIENTAL",
    },
    location: {
      name: "Formosa",
      state: "GO",
      coordinates: { lat: -15.5394, lng: -47.3316 },
    },
    coverImage: "/forest-drone-aerial-view.jpg",
    timeline: [
      {
        id: "tl-env-1",
        phase: "EXECUCAO",
        title: "Dados de impacto registrados",
        description: "Empresa registrou dados de 25.000 árvores plantadas",
        timestamp: new Date("2025-06-01T10:00:00"),
        actor: { id: "emp-1", name: "Coop. Terra Fértil", role: "Empresa Ambiental" },
      },
      {
        id: "tl-env-2",
        phase: "EXECUCAO",
        title: "30 sistemas instalados",
        description: "60% da meta concluída com evidências registradas",
        timestamp: new Date("2025-11-15T14:00:00"),
        hash: "sha256:sol123abc456...",
      },
      {
        id: "tl-env-3",
        phase: "CERTIFICACAO",
        title: "Certificação técnica aprovada",
        description: "Análise de solo, espécies e metodologia aprovada",
        timestamp: new Date("2025-07-01T16:00:00"),
        actor: { id: "cert-2", name: "Eng. Carlos Oliveira", role: "Analista Certificador" },
      },
      {
        id: "tl-env-4",
        phase: "INSCRICAO",
        title: "Inscrito no Bitcoin",
        description: "Registro imutável criado na blockchain Bitcoin",
        timestamp: new Date("2025-07-05T10:00:00"),
        data: { inscriptionId: "ord:env456xyz789abc012", blockHeight: 865432 },
      },
      {
        id: "tl-env-5",
        phase: "CONCLUIDO",
        title: "Impacto registrado no Hall",
        description: "Disponível no Hall de Impacto da STHATION",
        timestamp: new Date("2025-07-05T11:00:00"),
      },
    ],
    currentPhase: "CONCLUIDO",
    metrics: {
      totalInvested: 320000,
      beneficiaries: 0,
      carbonCredits: 75,
      impactUnits: 25000,
      impactUnit: "árvores plantadas",
      impactScore: 12500,
    },
    validation: {
      certifiersCount: 1,
      certifiersApproval: 100,
      validatedAt: new Date("2025-07-01T16:00:00"),
    },
    inscription: {
      txid: "env456xyz789abc012def",
      inscriptionId: "ord:env456xyz789abc012",
      inscribedAt: new Date("2025-07-05T10:00:00"),
      blockHeight: 865432,
    },
    status: "INSCRITO",
    createdAt: new Date("2025-06-01T10:00:00"),
    updatedAt: new Date("2025-07-05T11:00:00"),
    availableForTrading: true,
    tradingPlatformUrl: "https://trading.sthation.io/nobis/env456",
  },
  // Social em andamento (não inscrito ainda)
  {
    id: "impact-social-2",
    type: "SOCIAL",
    title: "Escola de Informática - Rocinha",
    description:
      "Curso de programação e alfabetização digital para 200 jovens da comunidade da Rocinha. Formação de 6 meses com certificação reconhecida e mentoria para inserção profissional.",
    category: "Educação e Qualificação",
    organization: {
      id: "inst-6",
      name: "Instituto Tech Social",
      logo: "/modern-tech-logo.png",
      type: "INSTITUICAO_SOCIAL",
    },
    location: {
      name: "Rocinha",
      state: "RJ",
      coordinates: { lat: -22.9879, lng: -43.2474 },
    },
    coverImage: "/children-reading-books-library.jpg",
    timeline: [
      {
        id: "tl-edu-1",
        phase: "CAPTACAO",
        title: "Projeto publicado para captação",
        description: "Card de captação publicado na plataforma STHATION",
        timestamp: new Date("2025-05-01T10:00:00"),
        actor: { id: "inst-6", name: "Instituto Tech Social", role: "Instituição" },
      },
      {
        id: "tl-edu-2",
        phase: "DOACAO",
        title: "Meta de captação atingida",
        description: "R$ 83.750 arrecadados de 312 doadores",
        timestamp: new Date("2025-06-15T14:30:00"),
        data: { totalRaised: 83750, donorsCount: 312 },
      },
      {
        id: "tl-edu-3",
        phase: "EXECUCAO",
        title: "Turmas iniciadas",
        description: "4 turmas de 50 alunos começaram a formação",
        timestamp: new Date("2025-07-01T08:00:00"),
        actor: { id: "inst-6", name: "Instituto Tech Social", role: "Instituição" },
      },
      {
        id: "tl-edu-4",
        phase: "CHECAGEM",
        title: "Validação por Checkers",
        description: "10 checkers validaram o projeto com 89% de consenso",
        timestamp: new Date("2025-11-20T16:00:00"),
        data: { checkersCount: 10, consensusPercent: 89 },
      },
      {
        id: "tl-edu-5",
        phase: "CERTIFICACAO",
        title: "Em análise pelo certificador",
        description: "Aguardando validação técnica final",
        timestamp: new Date("2025-12-01T11:00:00"),
        actor: { id: "cert-3", name: "Dra. Ana Costa", role: "Analista Certificador" },
      },
    ],
    currentPhase: "CERTIFICACAO",
    metrics: {
      totalInvested: 83750,
      beneficiaries: 200,
      impactUnits: 200,
      impactUnit: "jovens formados",
      impactScore: 9200,
    },
    validation: {
      checkersCount: 10,
      checkersApproval: 89,
      certifiersCount: 1,
      certifiersApproval: 0,
      validatedAt: new Date("2025-11-20T16:00:00"),
    },
    status: "EM_ANDAMENTO",
    createdAt: new Date("2025-05-01T10:00:00"),
    updatedAt: new Date("2025-12-01T11:00:00"),
    availableForTrading: false,
  },
  // Ambiental em andamento
  {
    id: "impact-ambiental-2",
    type: "AMBIENTAL",
    title: "Energia Solar Comunitária - Bahia",
    description:
      "Instalação de 50 sistemas de energia solar em comunidades rurais da Chapada Diamantina. Redução de custos energéticos e diminuição de emissões de carbono.",
    category: "Energia Renovável",
    organization: {
      id: "emp-2",
      name: "SolarTech Brasil",
      logo: "/solar-energy-logo.png",
      type: "EMPRESA_AMBIENTAL",
    },
    location: {
      name: "Chapada Diamantina",
      state: "BA",
      coordinates: { lat: -12.4614, lng: -41.4628 },
    },
    coverImage: "/tree-planting-evidence-photo.jpg",
    timeline: [
      {
        id: "tl-sol-1",
        phase: "EXECUCAO",
        title: "Projeto iniciado",
        description: "Empresa registrou início do projeto de instalação solar",
        timestamp: new Date("2025-09-01T10:00:00"),
        actor: { id: "emp-2", name: "SolarTech Brasil", role: "Empresa Ambiental" },
      },
      {
        id: "tl-sol-2",
        phase: "EXECUCAO",
        title: "30 sistemas instalados",
        description: "60% da meta concluída com evidências registradas",
        timestamp: new Date("2025-11-15T14:00:00"),
        hash: "sha256:sol123abc456...",
      },
    ],
    currentPhase: "EXECUCAO",
    metrics: {
      totalInvested: 180000,
      beneficiaries: 0,
      carbonCredits: 45,
      impactUnits: 30,
      impactUnit: "sistemas instalados",
      impactScore: 6800,
    },
    status: "EM_ANDAMENTO",
    createdAt: new Date("2025-09-01T10:00:00"),
    updatedAt: new Date("2025-11-15T14:00:00"),
    availableForTrading: false,
  },
]

// Projetos AMBIENTAIS publicos (para pagina /projetos tab ambientais)
// Esses sao projetos de empresas ambientais validados por Analistas Certificadores
export const mockPublicEnvironmentalProjects = [
  {
    id: "pub-env-1",
    title: "Compostagem Industrial Organa",
    description: "Processamento de 500 toneladas/mes de residuos organicos em adubo certificado. Reducao de 85% de metano em aterro.",
    category: "Economia Circular",
    tsbCategory: "TSB-03",
    location: { name: "Ubatuba", state: "SP" },
    budget: 380000,
    status: "CERTIFIED" as const,
    company: "Organa Sustentavel Ltda",
    sensors: 8,
    tco2eAvoided: 420,
    evidences: 12,
    certifiedBy: "Dr. Andre Ribeiro - CREA 654321",
    certificationDate: "2025-09-15",
  },
  {
    id: "pub-env-2",
    title: "Captacao Solar Fazenda Verde",
    description: "Geracao de 2.4 MWh/dia com paineis solares de alta eficiencia. Alimenta comunidade rural de 180 familias.",
    category: "Energia Renovavel",
    tsbCategory: "TSB-07",
    location: { name: "Petrolina", state: "PE" },
    budget: 520000,
    status: "EXECUTING" as const,
    company: "Solar Norte Energia S.A.",
    sensors: 4,
    tco2eAvoided: 310,
    evidences: 8,
    certifiedBy: null,
    certificationDate: null,
  },
  {
    id: "pub-env-3",
    title: "Biodigestor Fazenda Sol",
    description: "Conversao de dejetos suinos em biogas e biofertilizante. Capacidade de 15m3/dia de biogas.",
    category: "Mitigacao de Mudancas Climaticas",
    tsbCategory: "TSB-01",
    location: { name: "Chapeco", state: "SC" },
    budget: 290000,
    status: "NOBIS_EMITTED" as const,
    company: "AgroBio Solucoes Ltda",
    sensors: 6,
    tco2eAvoided: 185,
    evidences: 15,
    certifiedBy: "Dra. Camila Torres - CRBio 98765",
    certificationDate: "2025-06-20",
  },
  {
    id: "pub-env-4",
    title: "Reciclagem de Residuos Eletronicos",
    description: "Processamento e reciclagem de 20 toneladas/mes de lixo eletronico com rastreabilidade completa.",
    category: "Economia Circular",
    tsbCategory: "TSB-03",
    location: { name: "Campinas", state: "SP" },
    budget: 450000,
    status: "EXECUTING" as const,
    company: "EcoTech Reciclagem S.A.",
    sensors: 3,
    tco2eAvoided: 95,
    evidences: 6,
    certifiedBy: null,
    certificationDate: null,
  },
  {
    id: "pub-env-5",
    title: "Tratamento de Efluentes Industriais",
    description: "Sistema de tratamento biologico de efluentes com reuso de 90% da agua. Capacidade de 500m3/dia.",
    category: "Uso Sustentavel de Recursos Hidricos",
    tsbCategory: "TSB-02",
    location: { name: "Betim", state: "MG" },
    budget: 680000,
    status: "CERTIFIED" as const,
    company: "AquaPura Ambiental Ltda",
    sensors: 5,
    tco2eAvoided: 140,
    evidences: 10,
    certifiedBy: "Dr. Paulo Mendes - CRQ 112233",
    certificationDate: "2025-11-01",
  },
]
